#!/usr/bin/env bash

# check if runing as root user
if [ "$EUID" -ne 0 ]; then
	echo -e "This script needs to run as root user, please use \"sudo ./install\" instead";
	exit 1;
fi

# check if plymouth themes directory exist
if [ ! -d "/usr/share/plymouth/themes" ]; then
	echo -e "\"/usr/share/plymouth/themes\" directory dose not exist, are you sure plymouth is installed and up to date?";
	exit 1;
fi

# coping theme in /usr/share/plymouth/themes/
echo -n "coping theme in /usr/share/plymouth/themes/   ..................   " ;
mkdir -p /usr/share/plymouth/themes/logo-mac-style
cp -r `dirname $0` /usr/share/plymouth/themes/logo-mac-style ;
if [ $? -gt 0 ]; then
	echo -e "\nan error occoured in moving `dirname $0` to /usr/share/plymouth/themes/" ;
	exit 1;
fi
echo "[done]" ;

echo -n "setting s4rchiso as default plymouth theme   ..............   " ;
sudo plymouth-set-default-theme -R logo-mac-style
if [ $? -gt 0 ]; then
	echo -e "\nan error occoured setting alternative in /usr/share/plymouth/themes/default.plymouth";
	exit 1;
fi
echo "[done]" ;

echo "logo-mac-style is your plymouth theme now :)" ;

exit 0;
